name: "Deploy"
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@v12
    - name: "Build"
      run: nix-build -A website
    # NOTE Workaround for artifacts and deploy not liking symlinks to
    # read-only paths.
    - name: "Copy artifacts"
      run: "mkdir build && cp -r result/*  build/ && chmod +w -R build/"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

